language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - $ANDROID_TARGET

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-$ANDROID_TARGET

script:
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew installDebug

after_success:
  - bash echo "Perfection!"