language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    # Note that the tools section appears twice on purpose
    # as it’s required to get the newest Android SDK tools.
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.1

    # The SDK version used to compile your project
    - android-27

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

after_success:
  - bash echo "Perfection!"